version: "3.8"

services:
  n8n:
    build: .
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=173.212.225.35
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=http://173.212.225.35:5678
      - TESSDATA_PREFIX=/usr/share/tessdata
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
